### ISSUE TITLE
wrong number of arguments (given 7, expected 6)   for  decode_png_image_pass

### ISSUE THREAD

**Issue by avucic** [donv/capybara-screenshot-diff#82]
Hi, I get this error when i run the spec.
I have this in my Gemfile
```ruby
  gem "capybara-screenshot-diff"
  gem "oily_png", platform: :ruby
```
I installed `libvips`

In my spec

```ruby
        visit admin_users_path

        screenshot("welcome_index")
```

```
Failure/Error: decode_png_image_pass(stream, width, height, color_mode, depth, 0, decoding_palette)
                                                                                                   
ArgumentError:                                                                                     
  wrong number of arguments (given 7, expected 6)      

     # /Users/vucinjo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/chunky_png-1.4.0/lib/chunky_png/canvas/png_decoding.rb:120:in `decode_png_image_pass'
     # /Users/vucinjo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/chunky_png-1.4.0/lib/chunky_png/canvas/png_decoding.rb:120:in `decode_png_without_interlacing'
     # /Users/vucinjo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/chunky_png-1.4.0/lib/chunky_png/canvas/png_decoding.rb:99:in `decode_png_pixelstream'
     # /Users/vucinjo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/chunky_png-1.4.0/lib/chunky_png/canvas/png_decoding.rb:81:in `from_datastream'
     # /Users/vucinjo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/chunky_png-1.4.0/lib/chunky_png/image.rb:74:in `from_datastream'
     # /Users/vucinjo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/chunky_png-1.4.0/lib/chunky_png/canvas/png_decoding.rb:36:in `from_blob'
     # /Users/vucinjo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/capybara-screenshot-diff-1.7.1/lib/capybara/screenshot/diff/drivers/chunky_png_driver.rb:364:in `_load_images'
     # /Users/vucinjo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/capybara-screenshot-diff-1.7.1/lib/capybara/screenshot/diff/drivers/chunky_png_driver.rb:40:in `load_images'
     # /Users/vucinjo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/capybara-screenshot-diff-1.7.1/lib/capybara/screenshot/diff/image_compare.rb:81:in `different?'
     # /Users/vucinjo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/capybara-screenshot-diff-1.7.1/lib/capybara/screenshot/diff/test_methods.rb:96:in `assert_image_not_changed'
     # /Users/vucinjo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/capybara-screenshot-diff-1.7.1/lib/capybara/screenshot/diff.rb:99:in `block in track_failures'
     # /Users/vucinjo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/capybara-screenshot-diff-1.7.1/lib/capybara/screenshot/diff.rb:98:in `map'
     # /Users/vucinjo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/capybara-screenshot-diff-1.7.1/lib/capybara/screenshot/diff.rb:98:in `track_failures'
     # /Users/vucinjo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/capybara-screenshot-diff-1.7.1/lib/capybara/screenshot/diff.rb:87:in `block in included'
     # /Users/vucinjo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:457:in `instance_exec'
     # /Users/vucinjo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:457:in `instance_exec'
     # /Users/vucinjo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:372:in `run'
     # /Users/vucinjo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:529:in `block in run_owned_hooks_for'
     # /Users/vucinjo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:528:in `each'
     # /Users/vucinjo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:528:in `run_owned_hooks_for'
     # /Users/vucinjo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:615:in `block in run_example_hooks_for'
     # /Users/vucinjo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:614:in `each'
     # /Users/vucinjo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:614:in `run_example_hooks_for'
     # /Users/vucinjo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:485:in `run'
     # /Users/vucinjo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:518:in `run_after_example'
     # /Users/vucinjo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:283:in `block in run'
     # /Users/vucinjo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:511:in `block in with_around_and_singleton_context_hooks'
     # /Users/vucinjo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:468:in `block in with_around_example_hooks'
     # /Users/vucinjo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:486:in `block in run'
     # /Users/vucinjo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:626:in `block in run_around_example_hooks_for'
     # /Users/vucinjo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:352:in `call'
     # /Users/vucinjo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-rails-6.0.3/lib/rspec/rails/example/system_example_group.rb:120:in `block (2 levels) in <module:SystemExampleGroup>'
     # /Users/vucinjo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:457:in `instance_exec'
     # /Users/vucinjo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:457:in `instance_exec'
     # /Users/vucinjo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:390:in `execute_with'
     # /Users/vucinjo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
     # /Users/vucinjo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:352:in `call'
     # /Users/vucinjo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-rails-6.0.3/lib/rspec/rails/adapters.rb:75:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
     # /Users/vucinjo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:457:in `instance_exec'
     # /Users/vucinjo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:457:in `instance_exec'
     # /Users/vucinjo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:390:in `execute_with'
     # /Users/vucinjo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
     # /Users/vucinjo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:352:in `call'
     # /Users/vucinjo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <main>'
     # /Users/vucinjo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:457:in `instance_exec'
     # /Users/vucinjo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:457:in `instance_exec'
     # /Users/vucinjo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:390:in `execute_with'
     # /Users/vucinjo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
     # /Users/vucinjo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/example.rb:352:in `call'
     # /Users/vucinjo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:629:in `run_around_example_hooks_for'
     # /Users/vucinjo/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-core-3.12.2/lib/rspec/core/hooks.rb:486:in `run'
                                            
```
Any idea?
Thanks in advance

**Comment by avucic** [comment]
Sorry...my mistake. I added `  gem "ruby-vips"` to my Gemfile and now it works!
