### ISSUE TITLE
uninitialized constant Capybara::Screenshot

### ISSUE THREAD

**Issue by ibaralf** [donv/capybara-screenshot-diff#9]
Any reason why I get this error when I add **include Capybara::Screenshot::Diff**

Bundler installed your gem without issues
```bash
$ bundle install
...
Using capybara 3.10.0
Using chunky_png 1.3.11
Using capybara-screenshot-diff 0.13.1
Using ffi 1.9.25
Using childprocess 0.9.0
Using chromedriver-helper 2.1.0
...
```

But when I run the spec, I get this error for the include line
```ruby
spec/t1.rb:12:in `block in <top (required)>': uninitialized constant Capybara::Screenshot (NameError)
	from /Users/ibarraalfonso/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.4/lib/rspec/core/example_group.rb:385:in `module_exec'
```

I tried adding 
```ruby
require 'capybara-screenshot-diff'
```
but get a Cannot load file error

I also tried adding 
```ruby
require 'capybara/screenshot/diff/version'
require 'capybara/screenshot/diff/image_compare'
require 'capybara/screenshot/diff/test_methods'
```
This results in 
```ruby
NoMethodError:
       undefined method `screenshot' for #<RSpec::ExampleGroups::HomePage:0x007fa7bcc7c048>
     # ./spec/t1.rb:36:in `block (2 levels) in <top (required)>'
     # /Users/ibarraalfonso/.rvm/gems/ruby-2.3.1/gems/rspec-retry-0.5.2/lib/rspec/retry.rb:112:in `block in run'
```

MORE INVESTIGATIONS:
I tried directly using some of the class methods I found in the rubydocs and they seem to work fine.
```ruby
pry(#<StageSite>)> aa = Capybara::Screenshot::Diff::ImageCompare.new('pone.png', 'ptwo.png')
=> #<Capybara::Screenshot::Diff::ImageCompare:0x007fa3679072e0
 @annotated_new_file_name="pone_1.png~",
 @annotated_old_file_name="pone_0.png~",
 @area_size_limit=nil,
 @bottom=nil,
 @color_distance_limit=nil,
 @dimensions=nil,
 @left=nil,
 @max_color_distance=nil,
 @max_shift_distance=nil,
 @new_file_name="pone.png",
 @old_file_name="ptwo.png",
 @right=nil,
 @shift_distance_limit=nil,
 @top=nil>

[6] pry(#<StageSite>)> aa.different?
=> false
```

I'm quite sure your gem is installed since after the pry line, I checked if I can see access the methods
```ruby
  pry> Capybara::Screenshot::Diff.methods
   => [:delegate,
 :module_exec,
 :class_exec,
 :module_eval,
...```

But it does not have a screenshot method?

**Comment by tarragon** [comment]
Not sure if it will help you, but I had exactly the same issue and just solved if by adding the below to my Capybara helper file:

```
RSpec.configure do |config|
...
  config.include Capybara::Screenshot::Diff::TestMethods
...
```

**Comment by donv** [comment]
Guessing this can be closed now.
